# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# Use self hosted agent
pool:
  name: azure-container-apps-pool

steps:
- script: echo Getting AzDevOps busy!
  displayName: 'Run a one-line script'

- script: |
    echo This jobs are increasing the Job queue of AzDevOps what should result on
    echo KEDA autoscaling test
  displayName: 'KEDA autoscale'
